services:
  postgres:
    image: postgres:15 
    container_name: egrid-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=egrid-postgres
      - POSTGRES_PORT=5432
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: egrid-postgres-volume
